feature/personalization-details
bornfight/b-creative pull request #22
Opened 2021-10-20 12:14 UTC by tomislavjezidzic

Sitnice koje mogu podici dojam weba.

Trenutno sam se samo ovog sjetio, ako jos nesto mozemo dodati mi javite ili sami dodajte u PR.

2021-11-11 10:09 UTC, marioloncarek approved these changes

2021-11-11 10:37 UTC, ijurko approved these changes

2021-11-11 11:07 UTC, darko-komericki commented on generators/app/templates/static/scss/tools/_tools.scrollbar.scss
> +        width: 10px;
mozda staviti u variablu?

2021-11-11 11:07 UTC, darko-komericki commented on generators/app/templates/static/scss/tools/_tools.scrollbar.scss
> +        border-radius: 50px;
varijabla?

2021-11-11 11:08 UTC, darko-komericki approved these changes
Approvam uz par navedenih komentara.

2021-11-11 11:14 UTC, kvidek requested changes

2021-11-11 11:14 UTC, kvidek commented on generators/app/templates/static/scss/tools/_tools.scrollbar.scss
> +        width: 10px;
slozio bi se s @darko-komericki

2021-11-11 11:14 UTC, kvidek commented on generators/app/templates/static/scss/tools/_tools.scrollbar.scss
> +        border-radius: 50px;
slozio bi se s @darko-komericki

2022-06-30 17:01 UTC, ijurko commented
@tomislavjezidzic hocemo nastavit s ovim?

2022-07-01 06:30 UTC, tomislavjezidzic commented
ajmo iduci tjedan vidjeti sto cemo s time (ne meetu)

2024-02-29 11:32 UTC, closed without merging