Ratio utilities
bornfight/b-creative pull request #42
Opened 2023-07-07 12:23 UTC by kvidek

Added aspect ratio utility classes using "padding-bottom hack"

2023-07-09 18:45 UTC, marioloncarek requested changes

2023-07-09 18:45 UTC, marioloncarek commented on generators/app/templates/static/scss/utilities/_utilities.ratio.scss
> +@import "../settings/settings.ratio";
kaj nije ovo ukljuceno vec u settings? vidim import, znaci ovo je duplo

2023-07-09 18:45 UTC, marioloncarek commented
jel ovo zamjena za u-responsive-media?

2023-07-10 07:03 UTC, kvidek commented on generators/app/templates/static/scss/utilities/_utilities.ratio.scss
> +@import "../settings/settings.ratio";
totalno si u pravu, ma bed... fixam

2023-07-10 07:06 UTC, kvidek commented
> 

a nebi reko da je zamjena, vise neki globalni utility pa di god treba držat ratio il za mediu il za layout... al da, da nemamo duplo stvari, moze se na responsive medii napravit tweak i zamjenit ako mislis da je korisno/dobro.

2023-07-10 08:24 UTC, marioloncarek commented
meni je sve jasno sada, hvala, kaj se mene tice moze ostat da ne radimo dodatne komplikacije na responsive media

2023-07-10 08:33 UTC, merged