fluid function update
bornfight/b-creative pull request #44
Opened 2023-10-06 12:46 UTC by ijurko

+ css variables generating

2023-10-09 07:43 UTC, marioloncarek requested changes

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/tools/_tools.index.scss
> -/**
ostavio bi ovaj komentar samo "Third party tools", da ostane placeholder ako ce netko trebati ubacivati za neki projekt da ne ubaci na krivo mjesto

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/settings/_settings.spacings.scss
> + * big screen coefficient for fluid sizing, used for > xxl breakpoint
veliko B (Big screen...)

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/settings/_settings.spacings.scss
> + * Used for lowering sizes on big screens
malo u (used for...)

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/tools/_tools.fluid.scss
> + *
maknuti red razmaka

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/tools/_tools.fluid.scss
> + *
maknuti red razmaka

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/tools/_tools.fluid.scss
> + * Used In fluidValue mixin and fontSize mixin
malo u

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/tools/_tools.fluid.scss
> + * Use mixin instead
malo u

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/tools/_tools.fluid.scss
> + *
maknuti red razmaka

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/tools/_tools.fluid.scss
> + * Used In fluidValue mixin and fontSize mixin
malo u

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/tools/_tools.fluid.scss
> + * Use mixin instead
malo u

2023-10-09 07:43 UTC, marioloncarek commented on generators/app/templates/static/scss/tools/_tools.fluid.scss
> + * Used For Sizes > $breakpoint-xxl
malo u

2023-10-09 07:55 UTC, marioloncarek approved these changes

2023-10-09 08:39 UTC, ijurko commented on generators/app/templates/static/scss/tools/_tools.fluid.scss
> +}
razmisljam da sam ovo mogo spojit u jedno, ali cu imat par ifova vise i mozda nije potrebno, izgenerirat ce se opet isti kod, a ovako je citljivije

2023-10-10 12:20 UTC, darko-komericki approved these changes

2023-10-10 12:21 UTC, tomislavjezidzic approved these changes

2023-10-12 06:41 UTC, kvidek approved these changes

2023-10-13 08:08 UTC, merged